version: 1
formatters:
  simple:
    class: logging.Formatter
    format: "[%(asctime)s | %(levelname)s]: %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
handlers:
  stream_handler:
    class: logging.StreamHandler
    stream: ext://sys.stdout
    level: DEBUG
    formatter: simple
loggers:
  easyocr_logger:
    level: DEBUG
    handlers: [stream_handler]
    propagate: no
root:
  level: DEBUG
  handlers: [stream_handler]
